### ISSUE TITLE
missing ddl in `ch/ddl.go`

### ISSUE THREAD

**Issue by shawn0915** [pingcap/go-tpc#128]
when run `tiup bench ch prepare` will meet this error, shall we fix that?
```
a fatal occurred when preparing data: Error 1146: Table 'ch.order_line' doesn't exist
a fatal occurred when preparing data: Error 1146: Table 'ch.stock' doesn't exist
```

https://github.com/pingcap/go-tpc/blob/v1.0.8/ch/ddl.go

**Comment by mahjonp** [comment]
Sorry for your inconvenience. Ch benchmark is a load type that combines TPC-C and TPC-H schemas, including customer, District, history, item, and new_ Order, stock and other tables are defined by TPC-C schema. Therefore, https://github.com/pingcap/go-tpc#prepare-2 it is mentioned here that it needs to execute TPC-C prepare in advance to prepare the data of the above table before CH parts preparing. @shawn0915 

If you are interested, you can check the original paper https://research.tableau.com/sites/default/files/a8-cole.pdf

**Comment by mahjonp** [comment]
I check your PR https://github.com/pingcap/go-tpc/pull/129 , it may be possible to invoke TPC-C prepare related methods before ch prepare. @shawn0915

**Comment by shawn0915** [comment]
@mahjonp 您好，在官档：[如何对 TiDB 进行 TPC-C 测试](https://docs.pingcap.com/zh/tidb/stable/benchmark-tidb-using-tpcc)中，并没有明确介绍运行`tiup bench ch prepare`之前需要先运行`tiup bench tpcc prepare`，在`tiup bench ch --help`中也同样未介绍，而且不能直接调用`ch prepare`的方式不是很友好。

**Comment by mahjonp** [comment]
> @mahjonp 您好，在官档：[如何对 TiDB 进行 TPC-C 测试](https://docs.pingcap.com/zh/tidb/stable/benchmark-tidb-using-tpcc)中，并没有明确介绍运行`tiup bench ch prepare`之前需要先运行`tiup bench tpcc prepare`，在`tiup bench ch --help`中也同样未介绍，而且不能直接调用`ch prepare`的方式不是很友好。

赞同，此处 ping 下 @dbsid

**Comment by dbsid** [comment]
I have add a doc to show the instruction how to use go-tpc for CH benchmark https://github.com/pingcap/docs-cn/pull/10762/files
