### ISSUE TITLE
Feature Request: automatically reconnect to TiDB

### ISSUE THREAD

**Issue by kolbe** [pingcap/go-tpc#139]
The benchmark executor should automatically reconnect to TiDB and restart any aborted transactions if the connection to TiDB is broken.

High Availability is a core part of the TiDB value proposition, and any situation involving upgrading or failing over to another AZ/region will require applications to re-establish connections to TiDB, so our benchmarking tools should also support reconnections.

**Comment by zyguan** [comment]
Actually, it will automatically reconnect to TiDB if you run a workload with `--ignore-error`  (except for TPCH and will be fixed by #147).
